# docker-compose.yml

version: "3.9"

services:
  # Servicio de la API de FastAPI
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@db:5432/leaderboard_db
    depends_on:
      - db

  # Servicio de la Base de Datos PostgreSQL
  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=leaderboard_db

volumes:
  postgres_data: